# Generated by Django 4.0.4 on 2022-06-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_order_address_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='Address not available', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='Phone Not Provided', max_length=11),
        ),
    ]
